// Mocks generated by Mockito 5.4.5 from annotations
// in aliskanlik_takip/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aliskanlik_takip/models/aliskanlik.dart' as _i5;
import 'package:aliskanlik_takip/services/ayarlar_servisi.dart' as _i7;
import 'package:aliskanlik_takip/services/bildirim_servisi.dart' as _i6;
import 'package:aliskanlik_takip/services/veritabani_servisi.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTimeOfDay_0 extends _i1.SmartFake implements _i2.TimeOfDay {
  _FakeTimeOfDay_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VeritabaniServisi].
///
/// See the documentation for Mockito's code generation for more information.
class MockVeritabaniServisi extends _i1.Mock implements _i3.VeritabaniServisi {
  MockVeritabaniServisi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> aliskanlikEkle(_i5.Aliskanlik? aliskanlik) =>
      (super.noSuchMethod(
            Invocation.method(#aliskanlikEkle, [aliskanlik]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> aliskanlikGuncelle(_i5.Aliskanlik? aliskanlik) =>
      (super.noSuchMethod(
            Invocation.method(#aliskanlikGuncelle, [aliskanlik]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> aliskanlikSil(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#aliskanlikSil, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Aliskanlik>> tumAliskanliklarGetir() =>
      (super.noSuchMethod(
            Invocation.method(#tumAliskanliklarGetir, []),
            returnValue: _i4.Future<List<_i5.Aliskanlik>>.value(
              <_i5.Aliskanlik>[],
            ),
          )
          as _i4.Future<List<_i5.Aliskanlik>>);

  @override
  _i4.Future<_i5.Aliskanlik?> aliskanlikGetir(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#aliskanlikGetir, [id]),
            returnValue: _i4.Future<_i5.Aliskanlik?>.value(),
          )
          as _i4.Future<_i5.Aliskanlik?>);

  @override
  _i4.Future<void> durumGuncelle(String? id, bool? yeniDurum) =>
      (super.noSuchMethod(
            Invocation.method(#durumGuncelle, [id, yeniDurum]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BildirimServisi].
///
/// See the documentation for Mockito's code generation for more information.
class MockBildirimServisi extends _i1.Mock implements _i6.BildirimServisi {
  MockBildirimServisi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> bildirimPlanla(_i5.Aliskanlik? aliskanlik) =>
      (super.noSuchMethod(
            Invocation.method(#bildirimPlanla, [aliskanlik]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> bildirimIptalEt(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#bildirimIptalEt, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AyarlarServisi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAyarlarServisi extends _i1.Mock implements _i7.AyarlarServisi {
  MockAyarlarServisi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TimeOfDay get varsayilanHatirlatmaSaati =>
      (super.noSuchMethod(
            Invocation.getter(#varsayilanHatirlatmaSaati),
            returnValue: _FakeTimeOfDay_0(
              this,
              Invocation.getter(#varsayilanHatirlatmaSaati),
            ),
          )
          as _i2.TimeOfDay);

  @override
  bool get karanlikTema =>
      (super.noSuchMethod(Invocation.getter(#karanlikTema), returnValue: false)
          as bool);

  @override
  bool get bildirimAktif =>
      (super.noSuchMethod(Invocation.getter(#bildirimAktif), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> varsayilanHatirlatmaSaatiKaydet(_i2.TimeOfDay? saat) =>
      (super.noSuchMethod(
            Invocation.method(#varsayilanHatirlatmaSaatiKaydet, [saat]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> karanlikTemaKaydet(bool? karanlik) =>
      (super.noSuchMethod(
            Invocation.method(#karanlikTemaKaydet, [karanlik]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> bildirimAktifKaydet(bool? aktif) =>
      (super.noSuchMethod(
            Invocation.method(#bildirimAktifKaydet, [aktif]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
